[build]
  publish = "public"
  command = "npm run build"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Expose-Headers = "ETag"
    Access-Control-Allow-Headers = "If-None-Match"
